# Generated by Django 6.1.1 on 2026-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
